### ISSUE TITLE
Governor tunables issue path:"/sys/devices/system/cpu/cpufreq",

### ISSUE THREAD

**Issue by Pafcholini** [AndreiLux/Synapse#46]
http://www.mediafire.com/view/im4sb992ild0jtr/Screenshot_2015-01-10-00-01-10.png

I'm using the Note 4 with TW rom and in the directory /sys/devices/system/cpu/cpufreq there are 3 folders; "cpufreq_limit" "interactive (or gov that use in this moment) and "stats". When I try to make the Governor tunables with this directory path:"/sys/devices/system/cpu/cpufreq", Synapse gets FC. How I can exclude those 2 folders? I used your governor tunables from the wiki for my Note 2 but I can't fix it for the Note 4.
How can be solved this?
Thanks in advance.

**Comment by AndreiLux** [comment]
```exclude: [ "cpufreq_limit", "stats" ]```

In the top tree.

**Comment by Pafcholini** [comment]
Thanks. Now everything's great!
