### ISSUE TITLE
Settings option to hide descriptions

### ISSUE THREAD

**Issue by mkaluza** [AndreiLux/Synapse#49]
Descriptions are sometimes long and take up a lot of space and once you read all of them (or you're an advanced user), you don't need them. It would be nice to have the ability to hide them all.

**Comment by AndreiLux** [comment]
This is a problem of developers putting in ridiculous descriptions in the configurations, they should know better and you should take it up with them. I don't see the need to include such a workaround to a an issue that isn't really caused by the app.

**Comment by mkaluza** [comment]
It's not an issue, it's an enhancement - partially you're right, but even if descriptions are brief and well written, someone might not want/need them. What then? Modify entire config? Or should devs make 2 versions? Lame/Pro? And that way one switch would fix it...
