### ISSUE TITLE
[minor suggestion] adding a changelog somewhere

### ISSUE THREAD

**Issue by ghost** [AndreiLux/Synapse#63]
<a href="https://gist.github.com/eladkarako/c724bdfafa1726b2d6976ee8faf4b5b1#file-changelog-txt">https://gist.github.com/eladkarako/c724bdfafa1726b2d6976ee8faf4b5b1#file-changelog-txt</a>

**Comment by AndreiLux** [comment]
You know you have a freaking commit history?... https://github.com/AndreiLux/Synapse/commits/master

**Comment by ghost** [comment]
<img src="https://i.imgur.com/GzwffFo.gif"/>
<sub>I'm so <em>freaking</em> sorry...<br/>but consider that it is not intend of my a$$h0le,<br/>but for the bv77h0les of all your other cr^ppy users,<br/>whom l0ves your product, and to which, the<br/>GitHub's commit-log is a bit to high-end/low-level/inaccessible  for..<br/>Ps.<br/>personally I t00 think Synapse is pretty aꝡ︎esome!<br/>so please accept my f*cꡏ︎ing apology<br/></sub>
